###########################
# ESTADISTICA DESCRIPTIVA #
###########################

# EJERCICIO 1
# INSTALAR(SI CORRESPONDE) Y ACTIVAR LAS SIGUIENTES LIBRERIAS
# readxl
# skimr
# epiDisplay
# dplyr
# stringr

# EJERCICIO 2
# CARGAR LA BASE DE DATOS base_2022
# INCLUYA EL CODIGO EN EL SCRIPT


# ANALISIS DESCRIPTIVO DE VARIABLES CUANTITATIVAS
skim(data)
# EL PAQUETE skimr NOS PERMITE USAR LA FUNCION skim() 
# QUE NOS DA UN RESUMEN DE TODAS LAS VARIABLES EN NUESTRA BASE DE DATOS
# AQUI NOS PODEMOS DAR CUENTA DE VARIAS COSAS
# EN PRIMER LUGAR, ALGUNAS VARIABLES QUE DEBERIAN SER CUANTITATIVAS SON TOMADAS COMO CHARACTER
# EJEMPLO
class(nota_prerrequisito) # NOTEMOS QUE ESTO DA UN ERROR
# DICE QUE NO ENCUENTRA ESA VARIABLE
# ESO OCURRE PORQUE CUANDO TRABAJAMOS CON DATA FRAME, Y QUEREMOS
# "LLAMAR" A UNA VARIABLE ESPECÍFICA DEL DATA FRAME
# DEBEMOS UTILIZAR UN SIGNO PESO $
class(data$nota_prerrequisito)

# EJERCICIO 3 
# USAR EL COMANDO class() PARA OBSERVAR
# LA CLASE DE LAS VARIABLES QUE DEBERIAN SER CUANTITATIVAS



# CUANDO R NO LEE BIEN LA NATURALEZA DE NUESTRAS VARIABLES
# DEBEMOS TRANSFORMARLAS A LA NATURALEZA QUE CORRESPONDA
# EN CLASES ANTERIORES, VIMOS QUE EL VERBO MUTATE DEL PAQUETE dplyr
# NOS SIRVE PARA CREAR COLUMNAS NUEVAS
# PERO TAMBIEN NOS SIRVE PARA SOBREESCRIBIR VARIABLES QUE YA EXISTEN
# PARA HACER ESO, SOLO DEBEMOS PONERLE EL MISMO NOMBRE QUE TENIAN ANTES
# EL COMANDO as.numeric() nos permite transformar una variable a numerica

data <- data %>%
  mutate(nota_prerrequisito = as.numeric(nota_prerrequisito))
#Warning message:
#  Problem while computing `nota_prerrequisito = as.numeric(nota_prerrequisito)`.
# NAs introduced by coercion 
# AL PARECER ESTO NO FUNCIONA
# LO QUE PASA, ES QUE R NO PUEDE TRANSFORMAR A NUMERICA UNA VARIABLE QUE USA
# COMAS EN LOS DECIMALES, POR LO TANTO, ANTES DE TRANSFORMAR, DEBEMOS SUSTITUIR
# LAS COMAS POR PUNTOS.
# PERO COMO YA ARRUINAMOS LA BASE DE DATOS (PORQUE LA SOBREESCRIBIMOS) 
# DEBEMOS CARGARLA DENUEVO

# EJERICIO 4:
# CARGAR LA BASE DE DATOS base_2022

# EL COMANDO QUE NECESITAMOS ES str_replace_all() 
str_replace_all(data$nota_prerrequisito,",",".")
# PODEMOS VER QUE PRIMERO VA LA VARIABLE QUE QUEREMOS MODIFICAR
# DESPUES EL ELEMENTO QUE QUEREMOS CAMBIAR (COMA) Y POR ULTIMO
# AGREGAMOS EL ELEMENTO POR EL QUE QUEREMOS SUSTITUIR
# AHORA, VAMOS A MEZCLAR TODO: mutate, as.numeric y str_replace_all

data <- data %>%
  mutate(nota_prerrequisito = as.numeric(str_replace_all(nota_prerrequisito,",",".")))
# AHORA REVISEMOS SI QUEDA BIEN
class(data$nota_prerrequisito)
# COOL O NO?

# PARA QUE NECESITAMOS HACER TODO ESTO?
# PORQUE SI R NO SABE QUE ES UNA VARIABLE CUANTITATIVA
# NO PODEMOS TRABAJARLA COMO TAL
# POR EJEMPLO, EL COMANDO mean() NOS DA LA MEDIA ARITMETICA DE UNA VARIABLE
mean(data$nota_1)
# Warning message:
# In mean.default(data$nota_1) :
#  argument is not numeric or logical: returning NA


# EJERCICIO 5
# TRANSFORMAR A NUMERICA TODAS LAS VARIABLES QUE 
# DEBERIAN SER CUANTITATIVAS
# PRIMERO IDENTIFIQUEN CUALES SON ESAS VARIABLES, DESPUES REEMPLAZAN

####################################################
# ESTADISTICA DESCRIPTIVA PARA VARIABLES NUMERICAS #
####################################################

# UNA FUNCION UTIL QUE VIENE DE BASE EN R ES summary()
# NOS SIRVE PARA SACAR ESTADISTICA DESCRIPTIVA DE VARIABLES CUANTITATIVAS
summary(data$nota_prerrequisito)
# ESTO NOS DA LA SIGUIENTE INFORMACION
# EL MINIMO
# CUARTIL 1, 2 Y 3
# MEDIA
# MAXIMO
# NUMERO DE VALORES PERDIDOS

# TAMBIEN PODEMOS USAR DPLYR PARA SACAR ESTADISTICA DESCRIPTIVA
# UTILIZANDO EL VERBO summarise() o summarize()
data %>%
  summarise(media = round(mean(nota_prerrequisito, na.rm = T),2),
            sd = round(sd(nota_prerrequisito, na.rm = T),2),
            min = min(nota_prerrequisito, na.rm = T),
            max = max(nota_prerrequisito, na.rm = T))
# LA NOTA DE ESTADISTICA TIENE MUCHA O POCA DISPERSION?

####################################################
# ESTADISTICA DESCRIPTIVA PARA VARIABLES NOMINALES #
####################################################

# UN COMANDO MUY UTIL PARA SACAR TABLAS DE FRECUENCIA ES tab1()
tab1(data$consume)
# 4 PERSONAS QUE CONSUMEN, REPRESENTAN EL 13,8%

# AHORA TENEMOS OTRO PROBLEMA, DEBEMOS ELIMINAR EL PORCENTAJE
# QUE APORTAN LOS NA A LA TABLA, SI QUIERO ESTIMAR LA PREVALENCIA DE CONSUMO
# DEBO DEJAR FUERA A LOS QUE NO RESPONDIERON
# tab1() TIENE UN ARGUMENTO QUE SE LLAMA missing, POR DEFECTO ES TRUE,
# POR LO TANTO, DEBEMOS PONERLE FALSE PARA QUE NO NOS MUESTRE
# LOS VALORES PERDIDOS
tab1(data$consume, missing = FALSE)
# NOS TENEMOS QUE FIJAR EN LA COLUMNA QUE DICE %(NA-)
# EL 15,4% DE LOS ALUMNOS DECLARO CONSUMIR ALGUNA SUSTANCIA
# NO PUEDO SABER SI HAY GENTE QUE MINTIO.

# EJERCICIO 6
# HACER TABLAS DE FRECUENCIA PARA TODAS LAS VARIABLES NOMINALES
# INTERPRETAR LOS RESULTADOS

##################################
# ANALISIS DESCRIPTIVO BIVARIADO #
##################################


# MUCHAS VECES NOS INTERESARA DESCRIBIR LA RELACION ENTRE DOS VARIABLES
# DPLYR NOS AYUDA MUCHO CON ESO
# PODEMOS VINCULAR UNA VARIABLE NOMINAL CON UNA CUANTITATIVA
data %>%
  filter(!is.na(consume)) %>% # ESTE FILTRO NOS AYUDA PARA NO TOMAR EN CUENTA VALORES NA
  group_by(consume) %>% # AGRUPAMOS EN TORNO A UNA VARIABLE NOMINAL, ESTO PARA PODER COMPARAR
  summarise(media = mean(nota_prerrequisito),
            mediana = median(nota_prerrequisito),
            sd = sd(nota_prerrequisito),
            min = min(nota_prerrequisito),
            max = max(nota_prerrequisito))

# EJERCICIO 7
# RESPONDER ESTAS PREGUNTAS UTILIZANDO ANALISIS BIVARIADO CON DPLYR
# HAY DIFERENCIAS EN LA NOTA 1 ENTRE AQUELLOS QUE CONSUMEN Y LOS QUE NO CONSUMEN?
# HAY DIFERENCIAS DE RENDIMIENTO ENTRE MASC Y FEM?

